import { promises as fs } from "node:fs";
import path from "node:path";

const IGNORE = `# Generated by anti-default init
node_modules/
.next/
dist/
build/
out/
coverage/
*.min.js
*.min.css

# Disable a rule for this project:
# rule:rule-id
`;

const WORKFLOW = `name: Anti-Default

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  inclusive-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: NomadBuilder/anti-default@v1
        with:
          changed-from: \${{ github.event.pull_request.base.sha }}
          format: json
          output-file: anti-default-report.json
          comment-on-pr: "true"
`;

export const SKILL = `---
name: anti-default
description: Reviews public-facing copy, documentation, UI text, and code strings for inclusive-language defaults using the Anti-Default CLI. Use after writing or editing user-facing language, before publishing content, or when reviewing a pull request for thoughtful and inclusive wording.
---

# Anti-Default

## Workflow

1. Run \`npx anti-default . --format json --fail-on never\`.
2. Read each finding in its surrounding context.
3. Fix clear, unambiguous findings in user-facing language.
4. For identity, quoted, historical, legal, or self-descriptive language, explain the finding and ask before changing it.
5. Do not rewrite identifiers, APIs, proper names, quotations, or community self-description without confirmation.
6. Run the scan again and report what remains.

Respect \`.antidefaultignore\` and \`.antidefaultbaseline.json\`. Suggestions are starting points; context and the named community's own language take priority.
`;

async function writeIfMissing(
  filePath: string,
  contents: string,
): Promise<boolean> {
  try {
    await fs.access(filePath);
    return false;
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, contents, "utf8");
    return true;
  }
}

export async function initializeProject(cwd: string): Promise<string[]> {
  const created: string[] = [];
  const files: Array<[string, string]> = [
    [".antidefaultignore", IGNORE],
    [".github/workflows/anti-default.yml", WORKFLOW],
    [".cursor/skills/anti-default/SKILL.md", SKILL],
  ];

  for (const [relative, contents] of files) {
    if (await writeIfMissing(path.join(cwd, relative), contents)) {
      created.push(relative);
    }
  }

  const packagePath = path.join(cwd, "package.json");
  try {
    const raw = await fs.readFile(packagePath, "utf8");
    const pkg = JSON.parse(raw) as {
      scripts?: Record<string, string>;
      [key: string]: unknown;
    };
    pkg.scripts ??= {};
    if (!pkg.scripts["inclusive-check"]) {
      pkg.scripts["inclusive-check"] = "npx --yes anti-default .";
      await fs.writeFile(packagePath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
      created.push("package.json script: inclusive-check");
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw new Error(
        `Could not update package.json: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }

  return created;
}
