import { promises as fs } from "node:fs";
import path from "node:path";
import { AGENTS_URL, CLAUDE_PROJECT_INSTRUCTIONS, MCP_CONFIG_JSON } from "../lib/agent-install";
import { AFTER_EDIT_HOOK_SCRIPT } from "./hook-script";
import { SKILL as BUNDLED_SKILL } from "./skill-text";

const IGNORE = `# Generated by un-default init
node_modules/
.next/
dist/
build/
out/
coverage/
*.min.js
*.min.css
.undefaultfeedback.jsonl
un-default-report.json
un-default.sarif

# Disable a rule for this project:
# rule:rule-id
`;

const WORKFLOW = `name: Un-Default

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  inclusive-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: NomadBuilder/anti-default@v1
        with:
          changed-from: \${{ github.event.pull_request.base.sha }}
          format: json
          output-file: un-default-report.json
          comment-on-pr: "true"
`;

const CLAUDE_SETTINGS = {
  hooks: {
    PostToolUse: [
      {
        matcher: "Edit|Write",
        hooks: [
          {
            type: "command",
            command:
              "${CLAUDE_PROJECT_DIR}/.claude/hooks/un-default-after-edit.sh",
            timeout: 60,
          },
        ],
      },
    ],
  },
};

const CURSOR_HOOKS = {
  version: 1,
  hooks: {
    afterFileEdit: [
      {
        command: ".cursor/hooks/un-default-after-edit.sh",
      },
    ],
    postToolUse: [
      {
        matcher: "Write|Edit",
        command: ".cursor/hooks/un-default-after-edit.sh",
      },
    ],
  },
};

async function writeIfMissing(
  filePath: string,
  contents: string,
  mode?: number,
): Promise<boolean> {
  try {
    await fs.access(filePath);
    return false;
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, contents, { encoding: "utf8", mode });
    return true;
  }
}

async function writeExecutableIfMissing(
  filePath: string,
  contents: string,
): Promise<boolean> {
  const created = await writeIfMissing(filePath, contents, 0o755);
  if (created) return true;
  try {
    await fs.chmod(filePath, 0o755);
  } catch {
    /* ignore */
  }
  return false;
}

function hasUnDefaultClaudeHook(settings: unknown): boolean {
  const hooks = (settings as { hooks?: { PostToolUse?: unknown[] } })?.hooks
    ?.PostToolUse;
  if (!Array.isArray(hooks)) return false;
  return JSON.stringify(hooks).includes("un-default-after-edit");
}

function hasUnDefaultCursorHook(config: unknown): boolean {
  return JSON.stringify(config ?? {}).includes("un-default-after-edit");
}

async function ensureClaudeSettings(cwd: string): Promise<string | null> {
  const settingsPath = path.join(cwd, ".claude", "settings.json");
  try {
    const raw = await fs.readFile(settingsPath, "utf8");
    const existing = JSON.parse(raw) as Record<string, unknown>;
    if (hasUnDefaultClaudeHook(existing)) return null;
    const hooks = {
      ...((existing.hooks as Record<string, unknown>) ?? {}),
    };
    const post = Array.isArray(hooks.PostToolUse)
      ? [...(hooks.PostToolUse as unknown[])]
      : [];
    post.push(...CLAUDE_SETTINGS.hooks.PostToolUse);
    hooks.PostToolUse = post;
    existing.hooks = hooks;
    await fs.writeFile(
      settingsPath,
      `${JSON.stringify(existing, null, 2)}\n`,
      "utf8",
    );
    return ".claude/settings.json (merged Un-Default PostToolUse hook)";
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
    await fs.mkdir(path.dirname(settingsPath), { recursive: true });
    await fs.writeFile(
      settingsPath,
      `${JSON.stringify(CLAUDE_SETTINGS, null, 2)}\n`,
      "utf8",
    );
    return ".claude/settings.json";
  }
}

async function ensureCursorHooks(cwd: string): Promise<string | null> {
  const hooksPath = path.join(cwd, ".cursor", "hooks.json");
  try {
    const raw = await fs.readFile(hooksPath, "utf8");
    const existing = JSON.parse(raw) as Record<string, unknown>;
    if (hasUnDefaultCursorHook(existing)) return null;
    const hooks = {
      ...((existing.hooks as Record<string, unknown>) ?? {}),
    };
    for (const key of ["afterFileEdit", "postToolUse"] as const) {
      const list = Array.isArray(hooks[key])
        ? [...(hooks[key] as unknown[])]
        : [];
      list.push(...(CURSOR_HOOKS.hooks[key] as unknown[]));
      hooks[key] = list;
    }
    existing.hooks = hooks;
    existing.version = existing.version ?? 1;
    await fs.writeFile(
      hooksPath,
      `${JSON.stringify(existing, null, 2)}\n`,
      "utf8",
    );
    return ".cursor/hooks.json (merged Un-Default after-edit hooks)";
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
    await fs.mkdir(path.dirname(hooksPath), { recursive: true });
    await fs.writeFile(
      hooksPath,
      `${JSON.stringify(CURSOR_HOOKS, null, 2)}\n`,
      "utf8",
    );
    return ".cursor/hooks.json";
  }
}

export async function initializeProject(cwd: string): Promise<string[]> {
  const created: string[] = [];
  const files: Array<[string, string]> = [
    [".undefaultignore", IGNORE],
    [".github/workflows/un-default.yml", WORKFLOW],
    [".cursor/skills/un-default/SKILL.md", BUNDLED_SKILL],
    [".cursor/mcp.json", MCP_CONFIG_JSON],
    [".claude/skills/un-default/SKILL.md", BUNDLED_SKILL],
    [".mcp.json", MCP_CONFIG_JSON],
    ["CLAUDE.md", `${CLAUDE_PROJECT_INSTRUCTIONS.trim()}\n`],
  ];

  for (const [relative, contents] of files) {
    if (await writeIfMissing(path.join(cwd, relative), contents)) {
      created.push(relative);
    }
  }

  for (const relative of [
    ".claude/hooks/un-default-after-edit.sh",
    ".cursor/hooks/un-default-after-edit.sh",
  ]) {
    if (
      await writeExecutableIfMissing(
        path.join(cwd, relative),
        AFTER_EDIT_HOOK_SCRIPT,
      )
    ) {
      created.push(relative);
    }
  }

  const claudeSettings = await ensureClaudeSettings(cwd);
  if (claudeSettings) created.push(claudeSettings);

  const cursorHooks = await ensureCursorHooks(cwd);
  if (cursorHooks) created.push(cursorHooks);

  const packagePath = path.join(cwd, "package.json");
  try {
    const raw = await fs.readFile(packagePath, "utf8");
    const pkg = JSON.parse(raw) as {
      scripts?: Record<string, string>;
      [key: string]: unknown;
    };
    pkg.scripts ??= {};
    let touched = false;
    if (!pkg.scripts["inclusive-check"]) {
      pkg.scripts["inclusive-check"] = "npx --yes anti-default .";
      touched = true;
      created.push("package.json script: inclusive-check");
    }
    if (!pkg.scripts["inclusive-fix"]) {
      pkg.scripts["inclusive-fix"] = "npx --yes anti-default fix .";
      touched = true;
      created.push("package.json script: inclusive-fix");
    }
    if (touched) {
      await fs.writeFile(packagePath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw new Error(
        `Could not update package.json: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }

  return created;
}

/** Printed after init so hosts land on the growth one-pager. */
export function initNextSteps(): string[] {
  return [
    "Claude/Cursor will now scan after file edits (hooks) — no extra user step.",
    "Optional: paste Project instructions / MCP from:",
    `  ${AGENTS_URL}`,
  ];
}
