import { promises as fs } from "node:fs";
import path from "node:path";
import { SKILL as BUNDLED_SKILL } from "./skill-text";

const IGNORE = `# Generated by anti-default init
node_modules/
.next/
dist/
build/
out/
coverage/
*.min.js
*.min.css
.antidefaultfeedback.jsonl
anti-default-report.json
anti-default.sarif

# Disable a rule for this project:
# rule:rule-id
`;

const WORKFLOW = `name: Anti-Default

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  inclusive-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: NomadBuilder/anti-default@v1
        with:
          changed-from: \${{ github.event.pull_request.base.sha }}
          format: json
          output-file: anti-default-report.json
          comment-on-pr: "true"
`;

const MCP = `{
  "mcpServers": {
    "anti-default": {
      "command": "npx",
      "args": ["-y", "anti-default", "mcp"]
    }
  }
}
`;

async function writeIfMissing(
  filePath: string,
  contents: string,
): Promise<boolean> {
  try {
    await fs.access(filePath);
    return false;
  } catch {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, contents, "utf8");
    return true;
  }
}

export async function initializeProject(cwd: string): Promise<string[]> {
  const created: string[] = [];
  const files: Array<[string, string]> = [
    [".antidefaultignore", IGNORE],
    [".github/workflows/anti-default.yml", WORKFLOW],
    [".cursor/skills/anti-default/SKILL.md", BUNDLED_SKILL],
    [".cursor/mcp.json", MCP],
  ];

  for (const [relative, contents] of files) {
    if (await writeIfMissing(path.join(cwd, relative), contents)) {
      created.push(relative);
    }
  }

  const packagePath = path.join(cwd, "package.json");
  try {
    const raw = await fs.readFile(packagePath, "utf8");
    const pkg = JSON.parse(raw) as {
      scripts?: Record<string, string>;
      [key: string]: unknown;
    };
    pkg.scripts ??= {};
    let touched = false;
    if (!pkg.scripts["inclusive-check"]) {
      pkg.scripts["inclusive-check"] = "npx --yes anti-default .";
      touched = true;
      created.push("package.json script: inclusive-check");
    }
    if (!pkg.scripts["inclusive-fix"]) {
      pkg.scripts["inclusive-fix"] = "npx --yes anti-default fix .";
      touched = true;
      created.push("package.json script: inclusive-fix");
    }
    if (touched) {
      await fs.writeFile(packagePath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw new Error(
        `Could not update package.json: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }

  return created;
}
